version: "2.2"
services:
  chatbot_telegram:
    image: gastonciancio4/chatbot_telegram:latest
    ports:
      - "8080:8080"
    environment:
      QAWIKI_ENDPOINT: http://query.qawiki.org/proxy/wdqs/bigdata/namespace/wdq/sparql
      WIKIBASE_ENDPOINT: https://query.wikidata.org/sparql
      QAWIKI_URL: http://qawiki.org/
      QAWIKI_ENTITY_SEARCH: http://qawiki.org/w/api.php?action=wbsearchentities&search={0}&language={1}&limit=7&format=json&origin=*
      WIKIDATA_ENTITY_SEARCH: https://www.wikidata.org/w/api.php?action=wbsearchentities&search={0}&language={1}&uselang={1}&limit=7&format=json&origin=*
      QAWIKI_ENTITY_PREFIX: http://qawiki.org/entity/
      LANGS:  '["en", "es"]'
      JOB_INTERVAL_MINUTES: 60
      API_KEY_TELEGRAM: ${API_KEY_TELEGRAM}
      DNS_SENTRY: ${DNS_SENTRY}
    volumes:
      - ./data:/app/static/cached_questions
